# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20171107_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
